#! /bin/bash
# autostarts applications on startup for xmonad


if [ "$(ps -C compton | tail --bytes=8)" = "compton" ]; then
	echo "Hello World!"
else
	hsetroot -solid "#000000" &
	feh --bg-scale ~/Pictures/backgrounds/Crysis-3-wallpaper-1920-x-1080.jpg
	nm-applet &
	# pasystray &
	ibus-daemon &
	mpd &
	volumeicon &
	xfce4-power-manager &
	compton -b
	conky &
	pcmanfm -d &
	skype &
	trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 8 --transparent true --alpha 0 --tint 0x000000 --height 16 &
fi

xrdb ~/.Xresources
