#! /bin/bash
# This is my own startup script for awesome
# This scripts runs everytime I boot into awesome

if [ "$(ps -C compton | tail --bytes=8)" = "compton" ]; then
	echo "Hello World!"
else
	#hsetroot -solid "#000000" &
	#feh --bg-scale ~/Pictures/backgrounds/xmonad-background.jpg
	nm-applet &
	#wicd-client --tray &
	# pasystray &
	#cmst &
	#connman-ui-gtk &
#	dropboxd &
#	pidgin &
	ibus-daemon -d -r -x -n awesome &
	mpd &
#	volumeicon &
#	xfce4-power-manager &
#	xcompmgr -r 0 -o 0 -D 5 -cfF &
	udiskie &
	compton -b
    pasystray -a &
#	cairo-compmgr &
#	pcmanfm -d &
#	skype &
	#trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 8 --transparent true --alpha 0 --tint 0x000000 --height 16 &

fi
xrdb ~/.Xresources
