#!/bin/bash
# simple script to set me up quickly

function defaultapps {
    $UPDATE
    $INSTALL firefox \
            keepassxc \
            vim \
            networkmanager \
            network-manager-applet \
            ibus \
            ibus-libpinyin \
            ibus-anthy \
            ibus-hangoul \
            puleaudio \
            pavucontrol
}

function selectdesktop {
    case $1 
}


