#! /bin/bash
# autostarts applications on startup for xmonad


if [ "$(ps -C compton | tail --bytes=8)" = "compton" ]; then
	echo "Hello World!"
else
	hsetroot -solid "#000000" &
	feh --bg-scale ~/.xmonad/background.jpg
	xsetroot -cursor_name arrow
	nm-applet &
	# pasystray &
	#connman-ui-gtk &
	ibus-daemon &
	udiskie &
	mpd &
	volumeicon &
	xfce4-power-manager &
#	xcompmgr -r 0 -o 0 -D 5 -cfF &
	compton -b &
	conky &
#	pcmanfm -d &
	skype &
	dropboxd &
	pidgin &
	trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --alpha 0 --tint 0x000000 --height 16 &
fi

xrdb ~/.Xresources
